import type { Metadata } from 'next';
import { Alan_Sans } from 'next/font/google';
import '~/shared/css/globals.css';

const geistSans = Alan_Sans({
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Sekolah Menyusui',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
